language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev
  - git submodule update --init --recursive
  - git clone git://github.com/communi/libcommuni.git
  - cd libcommuni && qmake -qt=qt5 && make && sudo make install && cd ..
cache: apt
script:
  - nproc
  - qmake -qt=qt5 -v
  - qmake -qt=qt5
  - make -j$(nproc)
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#communi"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} - %{build_url}"
    skip_join: true
